services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SU2orange!"
    ports:
      - "1434:1433"
    hostname: mssql
    volumes:
      - "mssql-2019-data:/var/opt/mssql"
    networks: 
      - "learndb_net"
  provisioner:    
    image: mafudge/learn-databases-provisioner:latest
    # dev/debug
    # build: provisioner/.
    environment:
      - "FLASK_APP=app.py"
      - "FLASK_ENV=development"
      - "SCHEMA_PATH=/app/schemas"
      - "SQL_CLIENT_HOST=mssql"
      - "SQL_CLIENT_PORT=1433"
      - "SQL_CLIENT_USER=sa"
      - "SQL_CLIENT_PASS=SU2orange!"
      - "SQL_CLIENT_CMD=/opt/mssql-tools18/bin/sqlcmd"
      - "RANDOM_SEED=0"
    ports: 
      - "5001:8000"
    links:
      - mssql
    volumes:
      # dev/debug
      #- "./provisioner/:/app/"
      - "./schemas:/app/schemas"
    networks: 
      - "learndb_net"
  sqlpad:
    image: sqlpad/sqlpad:7.4.3
    environment:
      - "SQLPAD_ADMIN=admin@admin.org"
      - "SQLPAD_ADMIN_PASSWORD=SU2orange!"
      - "SQLPAD_AUTH_DISABLED=True"
      - "SQLPAD_AUTH_DISABLED_DEFAULT_ROLE=admin"
    links:
      - mssql
    ports:
      - "5002:3000"
    volumes:
      - sqlpad-volume:/var/lib/sqlpad
    networks: 
      - "learndb_net"
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "5003:8080"
    links:
      - mssql
    networks:
      - "learndb_net"

volumes:
    mssql-2019-data:
    sqlpad-volume:

networks:
  learndb_net:
    driver: bridge
